demo:
    path: dioqa-api-connexion/demo
    methods: [GET]
    defaults:
      _controller: 'Dioqaapiconnexion\Controller\ApiController::action'

demo-create:
    path: dioqa-api-connexion/create
    methods: [GET, POST]
    defaults:
      _controller: 'Dioqaapiconnexion\Controller\DemoController::createAction'